import re
from collections import Counter

inputstr = """MWMQPNGMVLSLNVYARDEHVCCNMHGNWQKGFARRGQDCDEIHWGCMEPFMRCQGICINGMMSNQNENWVYTAALAYEAEVYYKHGQKDGTMFLYSVPARCVKMYAKKEKIRPTYNEGFCAGWTMGSWHKNHFNIMHKWDCCARHWLSYTQYSDDHSASMGYCTGKWKMGWWQYRCCTVENEDRTLHFHLCNTSEYDAKDHGSAYCKVQHNRAPFCFQTPYLDMESTDPMCVIHCRSLRPNYPQPEHLTQTQTMPVNKVSLAGWKRPFASPPNTLNSTNFIFVWAKRETCFAYLVQTQSGAASWWIRRATFILAKKLMMGGIYNCYMLKHHLWTHCFLMDELPHTYYVMYQSWMPSTERHFMWGLYYKFCPNAKKAAVRSQAGKATFAVQFPCTPNTYYNWSIAFKGNESQYGRKDMKNIVQTYCLMFSRYDPSCCVCERRHHKPIVSSCFTHAHIAMHNHCWFTKWMIYTPTIWGFTGQDFCGQNTMFGCPWTLVWWFWDPPQGEQWWCDHWDPRFSFYDYAAAEKGDLPDCPISDMIKMCQKKNCQLWISVNPAYIAWVPDMKFRCYPPKVFPIETSNERFSNMYDVHVMIGYSFYMNITRHHFSSISFKNMLFVHDRKILGSHFQRWNQVSDVDVEIGFCEQIMECLDSRFVHDQHHKSVITILSRFRISDACNWVCQSNMTRHNEHSRSYANRMPGQAGDHCYQYKEEYVMNTTPQIEIMNFQKDYKKSANQFISEIPTGYYFKQPFNASATPYQLWTTERKDRHLPAHSKDDIYYVDEVWAPKMSYDFCDFWHSPHRRAERTDHACKNILTWKALPDYHIDKMYRLAHSGERSRGGEIMQEDMDVHTKYPDCQVFDCKNQYQQAHQDKAERQQIRNGCWKHGEWWVRTPSCCYADNQPGDYVRRGHCTELCFKNIGDRDSRNEIAFEDEWPKWASFNLWLQYKKNEPSETTHKWAKVDCNKQMSNMWFPEGWYKFGRSAGPFWEKLFKCGNFS"""

r_to_p_str = '''UUU F      CUU L      AUU I      GUU V
    UUC F      CUC L      AUC I      GUC V
    UUA L      CUA L      AUA I      GUA V
    UUG L      CUG L      AUG M      GUG V
    UCU S      CCU P      ACU T      GCU A
    UCC S      CCC P      ACC T      GCC A
    UCA S      CCA P      ACA T      GCA A
    UCG S      CCG P      ACG T      GCG A
    UAU Y      CAU H      AAU N      GAU D
    UAC Y      CAC H      AAC N      GAC D
    UAA Stop   CAA Q      AAA K      GAA E
    UAG Stop   CAG Q      AAG K      GAG E
    UGU C      CGU R      AGU S      GGU G
    UGC C      CGC R      AGC S      GGC G
    UGA Stop   CGA R      AGA R      GGA G
    UGG W      CGG R      AGG R      GGG G '''
    
x = dict(re.findall('([A,U,C,G]{3}) ([A-Z]{1}   |Stop)', r_to_p_str.replace('\n','   ') + '  '))
aa_string_counts =  Counter([y.strip() for y in x.values()])
ans = 1
for aa in inputstr:
    ans = (ans * aa_string_counts[aa]) % 1000000

ans = (ans*3) % 1000000
    
print ans    