import re


myFilename = "/Users/siakhnin/Downloads/rosalind_revp (4).txt"

f = open(myFilename, 'r')
inputstr = f.read()

'''
inputstr=""">Rosalind_5635
CGCGTCTCACTAAAGCCGTTGATCCGGATACGAATCCTTATATAGAAGGGACGATGAGGC
TCAGCTTAAGATAATTGCCGTTTGGCGCGAGCTCTCCCTCGTTCATTCGGCTAGGGCCGA
ATATTGGGCGGATTGACGCGTCACGGTAGACCCACACGGTGTCGCCTAGCCACGCCCAAC
TTCGCGAGTCGAATTTACTATCTGGAAGTGTAATATTAGGTTAGCAGCGTGTCCGGCCGA
CACACAGATTTCAGCGCGCTTGCCCCGAGCGAACAGGAGATAAGTATGTATGTTAGTTGG
TGGTTAATGGTCAAACGTCACATCAGCCTCGAATCCCCCGCAGGTAAACATCCGCCTGGA
ATGCACTCCGTCGAGCGAAACGCCACGTTCCGTTGCTTTACGTTGACAAATGACTAGCGT
CCCGCTAACCCATCGTGAACACCGGACACTGTCGCACGATTTCGCTAGCGAATAAATAAG
GAACCTGTCACTCCCCGCCAGACACTCTCACGCAGGTGCGAAGCACGATTACTGGCGGGA
GAGGCCGGTATAGAAGAAAGAAGTCTCCCGGAGCCGAACATCAAGGGTGCCGTGATTAGT
TGTGCAACCCACTCTTCTTGTACTGCGGGGTATGTTCACTGGGGAGGTCGTAACACAGCT
ATTCATCGAGCTAGTACGCGGACCCGGTAAGGTGCAGTCACGATTTTTTGTTGCTGTCCT
TGTCACGCCAGCCGAATCCCTGTTTTCGTAACGCGTTGTCATGGTTTTCTTCAGGACTAA
TTGGGACTGGTGTATAGCGAATTCACAGTAGGCCACCAACTCAACACGTGGTGGTTTGGA
ACGACTGCGTAAGTGTGAAGTGAAGCCGAACTGTGCGCGTAGGTTGACTGCATGTATTCG
GTATATCTAATGGCAAAGGCAATACAATATAT
"""
'''
dna_str = ''
x = re.match('>Rosalind_[0-9]{4}',inputstr)
if x:
    dna_str = inputstr[x.end():].replace('\n','').strip()

complements = {'A':'T','C':'G','G':'C','T':'A'}

def allKmersOf(my_str, k):
    if len(my_str) >= k:
        for i in range(0,len(my_str) - k + 1):
            yield i+1, my_str[i:i+k]

def isReversePalindrome(my_str):
    for i in range(len(my_str) / 2):
        if my_str[i] != complements[my_str[-1*(i+1)]]:
            return False
        
    return True
for x in range(4,13,2):
    for i, kmer in allKmersOf(dna_str,x):
        if isReversePalindrome(kmer):
            print str(i) + " " + str(x)